# Generated by Django 4.1.2 on 2022-10-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo", old_name="catogory", new_name="category",
        ),
    ]
